<?php

function planefix($costs, $margin){
	$FIRST_CLASS = 10;
	$BUSINESS_CLASS = 30;
	$ECONOMY_CLASS = 280;

	$PRICE_FIRST = 10000;
	$PRICE_BUSINESS = 4000;
	$PRICE_ECONOMY = 500;

	$FILL_FIRST = 1;
	$FILL_BUSINESS = 0.8;
	$FILL_ECONOMY = 0.68;

	$FIRST_CLASS*$PRICE_FIRST;
	$BUSINESS_CLASS*$PRICE_BUSINESS;
	$ECONOMY_CLASS*$PRICE_ECONOMY;
}